// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.2

package models

import (
	"time"
)

type Agent struct {
	ID          int32
	Name        string
	Enable      int32
	TypeID      int32
	EventMaxAge int64
	PropJsonStr string
	CreateTime  time.Time
	Deleted     int32
}

type AgentRelation struct {
	ID         int32
	SrcAgentID int32
	DstAgentID int32
	Deleted    int32
}

type AgentType struct {
	ID          int32
	Name        string
	AllowInput  int32
	AllowOutput int32
	Deleted     int32
}

type Event struct {
	ID          int32
	JsonStr     string
	SrcAgentID  int32
	CreatedTime time.Time
	Deleted     int32
}
